(defun sub-list2 (list from &optional (to (list-length list)))
    (if (or (> to (list-length list) ) (= to 0) )
        (if(and (< from (list-length list)) (> from 0) ) 
            (sub-list list from) 
            (sub-list list 1)
        )
        (if (> from to) 
            '()
            (if(and (< from (list-length list)) (> from 0))
                (sub-list list from to)
                (sub-list list 1 to)
            )
        )
    )
)