(defun depth (lst)
    (if(atom lst)
        (car '(0))
        (if(> (list-length (cdr lst)) 0)
            (max  (+ (depth (car lst)) 1) (depth (cdr lst)) )
            (+ 1 (depth (car lst)) )
        )
    )
)

(print   (depth nil) )
(print   (depth 1) )
(print   (depth '(1)) )
(print   (depth '((2))) )
(print   (depth '((2)(3 (6))(4))) )